Repository VultureProject/darwin, pull requests merged in 2019-10, with the labels that each got.

#81 minor improvements to tests framework
  tests/core/base.py
  tests/filters/fconnection.py
  tests/manager_socket/monitor_test.py
  tests/manager_socket/update_test.py
  tests/manager_socket/utils.py
  tests/tools/output.py
Labels: easy, enhancement

#78 Changes to Core and manager/heartbeat (Fixes #77)
  manager/Services.py
  samples/base/Core.cpp
  samples/base/Core.hpp
  samples/base/Monitor.cpp
  samples/base/Monitor.hpp
  tests/core/base.py
  tests/manager_socket/utils.py
Labels: bug, enhancement, important, technical

#80 Change sprintf function into snprintf
  samples/base/Session.cpp
Labels: enhancement, technical

#92 Redis rework
  CMakeLists.txt
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fconnection/ConnectionSupervisionTask.hpp
  samples/fconnection/Generator.cpp
  samples/fconnection/Generator.hpp
  samples/fend/EndTask.cpp
  samples/fend/EndTask.hpp
  samples/fend/Generator.cpp
  samples/fend/Generator.hpp
  samples/flogs/Generator.cpp
  samples/flogs/Generator.hpp
  samples/flogs/LogsTask.cpp
  samples/flogs/LogsTask.hpp
  samples/fsession/Generator.cpp
  samples/fsession/Generator.hpp
  samples/fsession/SessionTask.cpp
  samples/fsession/SessionTask.hpp
  samples/ftanomaly/Generator.cpp
  samples/ftanomaly/Generator.hpp
  samples/ftanomaly/TAnomalyTask.cpp
  samples/ftanomaly/TAnomalyTask.hpp
  samples/ftanomaly/TAnomalyThreadManager.cpp
  samples/ftanomaly/TAnomalyThreadManager.hpp
  tests/core/redis.py
  tests/core/test.py
  tests/filters/flogs.py
  tests/tools/filter.py
  tests/tools/redis_utils.py
  toolkit/RedisManager.cpp
  toolkit/RedisManager.hpp
Labels: enhancement, important, technical, tests

#105 FILTERS:: make every filter return a certitude for each entry
  samples/base/Session.cpp
  samples/base/Session.hpp
  samples/fanomaly/AnomalyTask.cpp
  samples/fanomaly/AnomalyTask.hpp
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fconnection/ConnectionSupervisionTask.hpp
  samples/fconnection/Generator.cpp
  samples/fdga/DGATask.cpp
  samples/fdga/DGATask.hpp
  samples/fend/EndTask.cpp
  samples/fend/EndTask.hpp
  samples/fhostlookup/HostLookupTask.cpp
  samples/fhostlookup/HostLookupTask.hpp
  samples/finspection/ContentInspectionTask.cpp
  samples/finspection/ContentInspectionTask.hpp
  samples/flogs/Generator.hpp
  samples/flogs/LogsTask.cpp
  samples/flogs/LogsTask.hpp
  samples/fpythonexample/PythonExampleTask.cpp
  samples/freputation/ReputationTask.cpp
  samples/freputation/ReputationTask.hpp
  samples/fsession/SessionTask.cpp
  samples/fsession/SessionTask.hpp
  samples/ftanomaly/TAnomalyTask.cpp
  samples/ftanomaly/TAnomalyTask.hpp
  samples/fuseragent/UserAgentTask.cpp
  tests/filters/fconnection.py
  tests/tools/filter.py
  toolkit/FileManager.cpp
Labels: bug, enhancement, important

#111 USER_AGENT:: DEPRECATED:: remove 'user agent' filter from default set of compiled filters
  CMakeLists.txt
Labels: easy

#112 CONTENT_INSPECTION:: Check rules were added before launching filter
  samples/finspection/Generator.cpp
  tests/filters/fdga.py
Labels: bug, easy, enhancement, important
