Repository VultureProject/darwin, pull requests merged in 2019-08, with the labels that each got.

#6 Yara changes
  pkg/stage/+POST_INSTALL
  pkg/stage/home/darwin/conf/fcontent_inspection/VultureDefaultRules.yar
  pkg/stage/home/darwin/conf/fcontent_inspection/exampleRule.yar
  pkg/stage/home/darwin/conf/fcontent_inspection/fcontent_inspection.conf
  pkg/stage/home/darwin/scripts/update_yara_rules.sh
  pkg/stage/plist
Labels: easy

#9 YARA_RULES :: Fix :: change plist to reflect changes in previous commit
  pkg/stage/plist
Labels: bug

#11 Update README.md
  README.md
Labels: important

#3 Add threshold in filters
  manager/Services.py
  samples/base/Core.cpp
  samples/base/Core.hpp
  samples/base/Server.cpp
  samples/base/Server.hpp
  samples/base/Session.cpp
  samples/base/Session.hpp
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fdga/DGATask.cpp
  samples/fhostlookup/HostLookupTask.cpp
  samples/finspection/ContentInspectionTask.cpp
  samples/freputation/ReputationTask.cpp
  samples/fuseragent/UserAgentTask.cpp
Labels: enhancement

#19 merging dev into master
  README.md
  manager/Services.py
  pkg/stage/+POST_INSTALL
  pkg/stage/home/darwin/conf/darwin.conf
  pkg/stage/home/darwin/conf/fanomaly/fanomaly.conf
  pkg/stage/home/darwin/conf/fcontent_inspection/VultureDefaultRules.yar
  pkg/stage/home/darwin/conf/fcontent_inspection/exampleRule.yar
  pkg/stage/home/darwin/conf/fcontent_inspection/fcontent_inspection.conf
  pkg/stage/home/darwin/conf/fdecision/fdecision.conf
  pkg/stage/home/darwin/conf/fend/fend.conf
  pkg/stage/home/darwin/conf/fhostlookup/database.db
  pkg/stage/home/darwin/conf/fhostlookup/fhostlookup.conf
  pkg/stage/home/darwin/conf/freputation/freputation.conf
  pkg/stage/home/darwin/conf/fsession/fsession.conf
  pkg/stage/home/darwin/conf/ftanomaly/ftanomaly.conf
  pkg/stage/home/darwin/scripts/update_yara_rules.sh
  pkg/stage/plist
  samples/base/Core.cpp
  samples/base/Core.hpp
  samples/base/Server.cpp
  samples/base/Server.hpp
  samples/base/Session.cpp
  samples/base/Session.hpp
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fdga/DGATask.cpp
  samples/fend/Generator.cpp
  samples/fend/Generator.hpp
  samples/fhostlookup/Generator.cpp
  samples/fhostlookup/Generator.hpp
  samples/fhostlookup/HostLookupTask.cpp
  samples/finjection/Generator.cpp
  samples/finjection/Generator.hpp
  samples/finspection/ContentInspectionTask.cpp
  samples/freputation/Generator.cpp
  samples/freputation/Generator.hpp
  samples/freputation/ReputationTask.cpp
  samples/fsession/Generator.cpp
  samples/fsession/Generator.hpp
  samples/fuseragent/UserAgentTask.cpp
Labels: bug, enhancement

#27 ACCESS_LOG :: Remove access logs and replace with debug logs
  samples/base/Core.cpp
  samples/base/Logger.cpp
  samples/base/Logger.hpp
  samples/base/Session.cpp
  samples/base/Session.hpp
  samples/fanomaly/AnomalyTask.cpp
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fdga/DGATask.cpp
  samples/fhostlookup/HostLookupTask.cpp
  samples/finjection/InjectionTask.cpp
  samples/finspection/ContentInspectionTask.cpp
  samples/fpythonexample/PythonExampleTask.cpp
  samples/freputation/ReputationTask.cpp
  samples/fsession/SessionTask.cpp
  samples/fuseragent/UserAgentTask.cpp
Labels: easy, enhancement
