Repository VultureProject/darwin, pull requests merged in 2020-04, with the labels that each got.

#171 FIX::tests/requirements.txt::fix redis requirement
  tests/requirements.txt
Labels: bug

#172 RedisManager and Tanomaly improvements for clustering
  samples/base/AlertManager.cpp
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fconnection/Generator.cpp
  samples/fend/EndTask.cpp
  samples/fend/Generator.cpp
  samples/flogs/Generator.cpp
  samples/flogs/LogsTask.cpp
  samples/fsession/Generator.cpp
  samples/fsession/SessionTask.cpp
  samples/ftanomaly/Generator.cpp
  samples/ftanomaly/TAnomalyTask.cpp
  samples/ftanomaly/TAnomalyTask.hpp
  samples/ftanomaly/TAnomalyThreadManager.cpp
  samples/ftest/Generator.cpp
  samples/ftest/Generator.hpp
  samples/ftest/TestTask.cpp
  samples/ftest/TestTask.hpp
  tests/core/redis.py
  tests/filters/fconnection.py
  tests/filters/flogs.py
  tests/tools/filter.py
  tests/tools/redis_utils.py
  toolkit/RedisManager.cpp
  toolkit/RedisManager.hpp
  toolkit/ThreadManager.cpp
  toolkit/ThreadManager.hpp
Labels: bug, enhancement, important, technical, tests

#170 SESSION CLIENT RESPONSE IMPROVEMENTS
  samples/base/Session.cpp
  samples/base/Session.hpp
  samples/base/errors.hpp
  samples/fanomaly/AnomalyTask.cpp
Labels: bug, enhancement, important
