Repository VultureProject/darwin, pull requests merged in 2020-05, with the labels that each got.

#177 Fix content_inspection filter's example conf
  conf/fcontent_inspection/fcontent_inspection.conf.example
Labels: bug, easy

#175 BREAKING: HOSTLOOKUP UPDATE
  samples/fhostlookup/Generator.cpp
  samples/fhostlookup/Generator.hpp
  samples/fhostlookup/HostLookupTask.cpp
  samples/fhostlookup/HostLookupTask.hpp
  tests/filters/fhostlookup.py
Labels: enhancement, important

#173 CMAKE:: various improvements to cmake compilation
  CMakeLists.txt
  cmake/ARMA_FindACML.cmake
  cmake/ARMA_FindACMLMP.cmake
  cmake/ARMA_FindARPACK.cmake
  cmake/ARMA_FindBLAS.cmake
  cmake/ARMA_FindCBLAS.cmake
  cmake/ARMA_FindCLAPACK.cmake
  cmake/ARMA_FindLAPACK.cmake
  cmake/ARMA_FindMKL.cmake
  cmake/ARMA_FindOpenBLAS.cmake
  cmake/FindArmadillo.cmake
  cmake/FindFaup.cmake
  cmake/FindHiredis.cmake
  cmake/FindMLPACK.cmake
  cmake/FindTensorflow.cmake
  cmake/FindYara.cmake
  cmake/LICENSE.txt
  cmake/fanomaly.cmake
  cmake/fdga.cmake
  cmake/finspection.cmake
  cmake/ftanomaly.cmake
Labels: enhancement

#174 Move pull_request_template to .github/ to have it automatically on new PRs
  .github/pull_request_template.md
Labels: easy, enhancement

#178 CMAKE:: silence warnings, improve Tensorflow search
  cmake/FindFaup.cmake
  cmake/FindMlpack.cmake
  cmake/FindTensorflow.cmake
  cmake/FindYara.cmake
  cmake/fanomaly.cmake
  cmake/finspection.cmake
  cmake/ftanomaly.cmake
Labels: bug

#179 FIX JSON LOG FORMAT ERRORS
  samples/fconnection/ConnectionSupervisionTask.cpp
  samples/fconnection/Generator.cpp
  samples/fdga/DGATask.cpp
  samples/fdga/Generator.cpp
  samples/fend/Generator.cpp
  samples/fhostlookup/Generator.cpp
  samples/flogs/Generator.cpp
  samples/flogs/LogsTask.cpp
  samples/fpythonexample/Generator.cpp
  samples/freputation/Generator.cpp
  samples/fsession/Generator.cpp
  samples/fsofa/Generator.cpp
  samples/ftanomaly/Generator.cpp
  samples/ftanomaly/TAnomalyTask.cpp
  samples/ftest/Generator.cpp
  samples/fuseragent/Generator.cpp
  samples/fuseragent/UserAgentTask.cpp
  toolkit/PythonUtils.cpp
  toolkit/Validators.cpp
Labels: bug, important

#176 Add Dockerfile and workflow(s)
  .github/workflows/docker-dev.yml
  .github/workflows/docker-releases.yml
  docker/darwin
Labels: enhancement

#181 CORE:: Fix unsigned integer parsing in parameters
  samples/base/Core.cpp
  tests/core/base.py
Labels: bug, easy, technical

#182 MANAGER REQS:: add redis 3.3.11 to python requirements
  manager/requirements.txt
Labels: bug, easy

#186 ADD HOSTLOOKUP DB BACKWARD COMPATIBILITY
  samples/fhostlookup/Generator.cpp
  samples/fhostlookup/Generator.hpp
  samples/fhostlookup/HostLookupTask.cpp
  tests/filters/fhostlookup.py
  toolkit/Files.cpp
  toolkit/Files.hpp
Labels: important
